# ==============================================================
# language.psm1 - All user-visible text strings (PT and EN)
# ==============================================================
# WHAT THIS MODULE DOES:
#   Stores every string shown to the user in a nested hashtable.
#   Get-Text "KeyName" returns the string for the current language.
#   The language is set in main.ps1 via the selection dialog.
#
# STRUCTURE:
#   $Global:Texts = @{
#     PT = @{ "KeyName" = "Portuguese text" }
#     EN = @{ "KeyName" = "English text"    }
#   }
#
# KEY CATEGORIES:
#   UI.Menu.N    - Sidebar button labels (N = action number 1-13)
#   UI.Title.N   - Content area title shown when button is selected
#   UI.Desc.N    - Content area description shown when button is selected
#   UI.SectionX  - Sidebar section header labels (Comm/Prod/Sistema)
#   Step.App.*   - Progress step labels for app restart actions
#   Step.Clean.* - Progress step labels for cache cleanup (action 5)
#   Step.Net.*   - Progress step labels for network diagnostic (action 12)
#   Step.Diag.*  - Progress step labels for PC diagnostic (action 13)
#   AppClosing   - "Closing X..." messages used in Barra-Progresso calls
#   AppStarting  - "Starting X..." messages used in Barra-Progresso calls
#   System.*     - Strings used in system.psm1 result windows
#   Email*       - Strings for the support ticket email body
#
# TO ADD A NEW LANGUAGE:
#   1. Copy the EN block
#   2. Change "EN" to your language code (e.g. "ES", "FR")
#   3. Translate all values
#   4. Add a button for it in the language dialog in main.ps1
#
# TO ADD A NEW KEY:
#   Add the key to BOTH the PT and EN sections.
#   Keys missing from one language will return $null
#   (caught by the "if (-not $FuncaoExecutada)" guards in ui.psm1).
#
# ENCODING NOTE:
#   This file is ASCII only - no accented characters.
#   Special characters would corrupt the file when saved without BOM.
#   Text displayed in WPF handles Unicode fine; it's the .psm1 source
#   file encoding that must stay ASCII.
# ==============================================================

$Global:Language = "PT"

$Global:Texts = @{
    PT = @{
        # === Legacy console menu strings (kept for backward compatibility) ===
        MenuTitle   = "SUPORTE RAPIDO - TI"
        MenuIntro   = "Ola! Se voce esta enfrentando problemas no seu computador, temos algumas opcoes que podem ajudar."
        MenuChoose  = "Escolha o numero correspondente ao problema e pressione ENTER."
        MenuOptions = "As opcoes sao:"
        OptionExit  = "0 - Sair"
        VoltarMenu  = "Pressione ENTER ou B para voltar ao menu..."
        ResolvidoTitulo = "Agente de Suporte TI"
        ResolvidoTexto  = "Foi executada uma acao automatica de correcao.`n`nO problema foi resolvido?`n`n- Clique em Resolvido para voltar ao menu.`n- Clique em Nao resolvido para abrir um ticket."
        BtnResolvido    = "Resolvido - Voltar ao Menu"
        BtnNaoResolvido = "Nao resolvido - Abrir Ticket"
        DriverTitulo    = "Atualizacao de Driver Wi-Fi"
        DriverTexto     = "O driver de Wi-Fi esta desatualizado.`n`nO download foi iniciado.`nA instalacao precisa ser feita pelo time de TI.`n`nClique abaixo para abrir o ticket."
        BtnAbrirTicket  = "Abrir Ticket"
        EmailSubject         = "Execucao Self-Healing"
        EmailGreeting        = "Ola time de TI,"
        EmailEquipInfo       = "Informacoes do equipamento:"
        EmailUser            = "Usuario:"
        EmailMachine         = "Maquina:"
        EmailThanks          = "Obrigado."
        EmailExecuted        = "Executei a funcao:"
        EmailPersist         = "Porem o problema ainda persiste."
        EmailSupport         = "Peco apoio para continuidade do atendimento."
        EmailUnknownFunction = "Funcao nao identificada"
        LogoTitle            = "IT Support Agent"
        MenuOption1  = "1 - Problemas com 8x8 Work"
        MenuOption2  = "2 - Problemas com Outlook"
        MenuOption3  = "3 - Problemas com Google Drive"
        MenuOption4  = "4 - Problemas com Slack"
        MenuOption5  = "5 - PC travando (limpeza de cache e temporarios)"
        MenuOption6  = "6 - Problemas com Microsoft Teams"
        MenuOption7  = "7 - Internet lenta (Diagnostico de Rede automatico)"
        MenuOption8  = "8 - Diagnostico do Computador"
        ChooseOption = "Escolha uma opcao"
        # === App status messages (used in Barra-Progresso calls) ===
        TeamsRestarting = "Reiniciando Microsoft Teams..."
        TeamsClosing    = "Fechando Microsoft Teams..."
        TeamsStarting   = "Iniciando Teams..."
        SlackRestarting = "Reiniciando Slack..."
        SlackClosing    = "Fechando Slack..."
        SlackStarting   = "Iniciando Slack..."
        DriveRestarting = "Reiniciando Google Drive..."
        DriveClosing    = "Fechando Google Drive..."
        DriveStarting   = "Iniciando Google Drive..."
        DriveNotFound   = "Google Drive nao encontrado."
        OutlookClosing  = "Fechando Outlook..."
        OutlookStarting = "Iniciando Outlook..."
        "8x8Restarting" = "Reiniciando 8x8 Work..."
        "8x8Closing"    = "Fechando 8x8 Work..."
        "8x8Starting"   = "Iniciando 8x8 Work..."
        "8x8NotFound"   = "8x8 Work nao encontrado."
        ClickUpClosing  = "Fechando ClickUp..."
        ClickUpStarting = "Iniciando ClickUp..."
        ZoomClosing     = "Fechando Zoom..."
        ZoomStarting    = "Iniciando Zoom..."
        ZoomNotFound    = "Zoom nao encontrado neste computador."
        OneDriveClosing = "Fechando OneDrive..."
        OneDriveStarting= "Iniciando OneDrive..."
        OneDriveNotFound= "OneDrive nao encontrado neste computador."
        ChromeClosing   = "Fechando Google Chrome..."
        ChromeStarting  = "Iniciando Google Chrome..."
        ChromeNotFound  = "Google Chrome nao encontrado neste computador."
        WebexClosing    = "Fechando Cisco Webex..."
        WebexStarting   = "Iniciando Cisco Webex..."
        WebexNotFound   = "Webex nao encontrado neste computador."
        WhatsAppClosing = "Fechando WhatsApp..."
        WhatsAppStarting= "Iniciando WhatsApp..."
        WhatsAppNotFound= "WhatsApp nao encontrado neste computador."
        DropboxClosing  = "Fechando Dropbox..."
        DropboxStarting = "Iniciando Dropbox..."
        DropboxNotFound = "Dropbox nao encontrado neste computador."
        CleaningCache   = "Limpando cache..."
        AppNotFound     = "Aplicativo nao encontrado neste computador."
        # === Network diagnostic strings ===
        "NetworkRepairTitle"        = "DIAGNOSTICO E REPARO DE INTERNET"
        "TestingLatency"            = "Testando latencia..."
        "TestingDNS"                = "Testando DNS..."
        "NetworkResult"             = "RESULTADO"
        "AutoFixTitle"              = "AUTO CORRECAO"
        "NetworkProblemDetected"    = "Problema detectado. Executando reparos basicos..."
        "RepairsApplied"            = "Reparos aplicados."
        "InternetNormal"            = "Internet aparenta estar normal."
        "WifiCheckingTitle"         = "VERIFICANDO DRIVER WIFI"
        "WifiNotFound"              = "Adaptador WiFi nao encontrado."
        "WifiDriverNotFound"        = "Nao foi possivel localizar o driver WiFi."
        "WifiOutdated"              = "DRIVER WIFI DESATUALIZADO!"
        "WifiUpdated"               = "Driver WiFi atualizado."
        "WifiModelDetected"         = "Modelo detectado"
        "WifiDescription"           = "Descricao"
        "WifiManufacturer"          = "Fabricante"
        "WifiInstalledVersion"      = "Versao instalada"
        "WifiBaselineGeneric"       = "Modelo nao encontrado no baseline, usando baseline generico."
        "WifiMinimumRecommended"    = "Versao minima recomendada"
        "WifiOpenTicketInstruction" = "Abra um chamado para o IT para atualizar o driver Intel Wi-Fi."
        "FuncVerifyWifi"            = "Verificacao do Driver Wi-Fi"
        "WifiDriverTitle"           = "Driver Wi-Fi Desatualizado"
        "WifiDriverOutdatedMessage" = "O driver Wi-Fi esta desatualizado. Clique OK para abrir a pagina oficial da Intel e iniciar o download."
        WifiDriverTicketMessage     = "O driver Wi-Fi estava desatualizado. Download iniciado (Intel oficial). Instalacao precisa ser feita pelo time de TI."
        WifiDriverUpdateActionName  = "Download do Driver Wi-Fi iniciado"
        InterfaceLabel    = "Interface"
        TypeLabel         = "Tipo"
        LinkSpeedLabel    = "Velocidade do Link"
        AverageLatency    = "Latencia media"
        NoLatencyResponse = "Sem resposta de latencia"
        DnsOk             = "DNS funcionando corretamente."
        DnsProblem        = "Problema na resolucao de DNS."
        DnsFlushing       = "Limpando cache DNS..."
        IpRenewing        = "Renovando IP..."
        # === System diagnostic and cleanup strings ===
        "System.HeaderLine"             = "========================================"
        "System.DiagnosticTitle"        = "        DIAGNOSTICO DO COMPUTADOR"
        "System.LabelPC"                = "PC"
        "System.LabelWindows"           = "Windows"
        "System.CpuSection"             = "===== CPU ====="
        "System.CpuUsage"               = "Uso atual"
        "System.RamSection"             = "===== MEMORIA RAM ====="
        "System.RamTotal"               = "Total"
        "System.RamUsed"                = "Em uso"
        "System.RamFree"                = "Livre"
        "System.DiskSection"            = "===== DISCO C: ====="
        "System.DiskTotal"              = "Total"
        "System.DiskFree"               = "Livre"
        "System.DiskLowSpace"           = "ALERTA: Pouco espaco em disco!"
        "System.HealthTitle"            = "PC HEALTH SCORE"
        "System.HealthScore"            = "Saude do PC"
        "System.StatusLabel"            = "Status"
        "System.StatusGood"             = "BOM"
        "System.StatusWarning"          = "ATENCAO"
        "System.StatusCritical"         = "CRITICO"
        "System.UptimeTitle"            = "TEMPO DE ATIVIDADE DO SISTEMA"
        "System.UptimeLabel"            = "PC ligado ha"
        "System.Days"                   = "dias"
        "System.Hours"                  = "horas"
        "System.UptimeOk"               = "Tempo de atividade dentro do recomendado."
        "System.UptimeRestartQuestion"  = "Seu computador esta ligado ha"
        "System.RestartNow"             = "Deseja reiniciar agora?"
        "System.RestartWindowTitle"     = "IT Support Agent - Diagnostico do PC"
        "System.RestartCountdown"       = "Seu computador sera reiniciado em 40 segundos.`nSalve seus arquivos imediatamente."
        "System.RestartScheduledTitle"  = "IT Support Agent - Reinicio Programado"
        "System.RestartCancelled"       = "Reinicio cancelado pelo usuario."
        "System.DeepCleanQuestion"      = "Para uma limpeza mais profunda, alguns aplicativos precisam ser fechados.`n`nDeseja fechar automaticamente?"
        "System.DeepCleanTitle"         = "Limpeza Avancada de Cache"
        "System.CleanStart"             = "Iniciando limpeza de cache..."
        "System.DeepCleanMode"          = "Modo DEEP CLEAN ativado. Fechando aplicativos..."
        "System.SafeCleanMode"          = "Modo SAFE CLEAN (aplicativos permanecerao abertos)"
        "System.DeepCleaning"           = "Limpando profundamente"
        "System.Cleaning"               = "Limpando"
        "System.SpaceFreed"             = "Foram liberados"
        "System.SpaceFreedConsole"      = "Espaco liberado"
        "System.CleanFinishedTitle"     = "Limpeza Concluida"
        "System.CleanFinished"          = "Limpeza concluida."
        "System.DiagnosticFunctionName" = "Diagnostico do PC"
        "System.CleanFunctionName"      = "Limpeza de Cache e Temporarios"
        "System.CleanupFreedSpace"      = "Foram liberados"
        "System.CleanupTitle"           = "Limpeza Concluida"
        "UI.Welcome"         = "Bem-vindo"
        "UI.WelcomeSub"      = "Selecione uma opcao no menu lateral para iniciar."
        "UI.LogReady"        = "Pronto. Selecione uma acao no menu lateral."
        "UI.LogCleared"      = "Log limpo."
        "UI.LogStarting"     = "Iniciando"
        "UI.LogDone"         = "Concluido"
        "UI.LogResolved"     = "Problema marcado como RESOLVIDO."
        "UI.LogTicket"       = "Abrindo ticket de suporte..."
        "UI.LogExit"         = "Encerrando..."
        "UI.BtnRun"          = "Executar"
        "UI.BtnClear"        = "Limpar Log"
        "UI.Exit"            = "Sair"
        "UI.StatusIdle"      = "Aguardando"
        "UI.StatusRunning"   = "Executando..."
        "UI.StatusDone"      = "Concluido"
        "UI.StatusError"     = "Erro"
        "UI.ProgStarting"    = "Iniciando..."
        "UI.ProgDone"        = "Concluido"
        "UI.DialogDoneTitle" = "Acao Concluida"
        "UI.DialogDoneText"  = "O problema foi resolvido? Se nao, um ticket sera aberto automaticamente."
        # === Sidebar menu labels (N matches action number in switch) ===
        "UI.Menu.1"  = "Microsoft Teams"
        "UI.Menu.2"  = "Outlook"
        "UI.Menu.3"  = "Google Drive"
        "UI.Menu.4"  = "Slack"
        "UI.Menu.5"  = "Limpeza de Cache"
        "UI.Menu.6"  = "Zoom"
        "UI.Menu.7"  = "OneDrive"
        "UI.Menu.8"  = "Google Chrome"
        "UI.Menu.9"  = "Cisco Webex"
        "UI.Menu.10" = "WhatsApp"
        "UI.Menu.11" = "Dropbox"
        "UI.Menu.12" = "Diagnostico de Rede"
        "UI.Menu.13" = "Diagnostico do PC"
        "UI.Menu.14" = "Otimizar Registro"
        "UI.Menu.15" = "8x8 Work"
        "UI.Title.1" = "Microsoft Teams"
        "UI.Title.2" = "Microsoft Outlook"
        "UI.Title.3" = "Google Drive"
        "UI.Title.4" = "Slack"
        "UI.Title.5" = "Limpeza de Cache"
        "UI.Title.6" = "Zoom"
        "UI.Title.7" = "OneDrive"
        "UI.Title.8" = "Google Chrome"
        "UI.Title.9" = "Cisco Webex"
        "UI.Title.10"= "WhatsApp Desktop"
        "UI.Title.11"= "Dropbox"
        "UI.Title.12"= "Diagnostico de Rede"
        "UI.Title.13"= "Diagnostico do PC"
        "UI.Title.14"= "Otimizar Registro HKCU"
        "UI.Title.15"= "8x8 Work"
        "UI.Desc.1"  = "Encerra e reinicia o Teams. Corrige chamadas, status e carregamento."
        "UI.Desc.2"  = "Fecha e reinicia Outlook. Corrige sincronizacao e problemas de inicializacao."
        "UI.Desc.3"  = "Reinicia Google Drive File Stream. Corrige arquivos que nao sincronizam."
        "UI.Desc.4"  = "Reinicia Slack. Corrige notificacoes e mensagens que nao carregam."
        "UI.Desc.5"  = "Limpa arquivos temporarios, cache do navegador e lixeira."
        "UI.Desc.6"  = "Encerra e reinicia Zoom. Corrige audio, video e problemas de conexao."
        "UI.Desc.7"  = "Reinicia OneDrive. Corrige sincronizacao de arquivos com o servidor."
        "UI.Desc.8"  = "Reinicia Chrome e limpa cache. Corrige lentidao e erros de carregamento."
        "UI.Desc.9"  = "Encerra e reinicia Webex. Corrige audio, video e erros de reuniao."
        "UI.Desc.10" = "Reinicia WhatsApp Desktop. Corrige mensagens que nao carregam."
        "UI.Desc.11" = "Reinicia Dropbox. Corrige sincronizacao de arquivos."
        "UI.Desc.12" = "Testa latencia, DNS e driver Wi-Fi. Repara automaticamente se possivel."
        "UI.Desc.13" = "Mostra CPU, RAM, disco, saude do PC e tempo de atividade."
        "UI.Desc.14" = "Limpa entradas MRU, chaves orfas e variaveis temporarias do registro de usuario."
        "UI.Desc.15" = "Encerra e reinicia o 8x8 Work. Corrige chamadas, audio e problemas de conexao VoIP."
        "UI.SectionComm"  = "COMUNICACAO"
        "UI.SectionProd"  = "PRODUTIVIDADE"
        "UI.SectionApps"  = "APLICATIVOS"
        # === Progress step labels (displayed below the donut during execution) ===
        "Step.App.Close"      = "Fechando aplicativo..."
        "Step.Waiting"        = "Aguardando..."
        "Step.App.Start"      = "Iniciando aplicativo..."
        "Step.Clean.Scan"     = "Verificando cache..."
        "Step.Clean.Apps"     = "Fechando aplicativos..."
        "Step.Clean.Temp"     = "Limpando temporarios..."
        "Step.Clean.Browser"  = "Limpando cache do navegador..."
        "Step.Clean.Recycle"  = "Esvaziando lixeira..."
        "Step.Net.Interface"  = "Detectando interface..."
        "Step.Net.Latency"    = "Testando latencia..."
        "Step.Net.DNS"        = "Testando DNS..."
        "Step.Net.Repair"     = "Executando reparo automatico..."
        "Step.Net.Wifi"       = "Verificando driver Wi-Fi..."
        "Step.Diag.SysInfo"   = "Coletando informacoes do sistema..."
        "Step.Diag.CPU"       = "Lendo uso de CPU..."
        "Step.Diag.RAM"       = "Lendo memoria RAM..."
        "Step.Diag.Disk"      = "Lendo disco..."
        "Step.Diag.Health"    = "Calculando health score..."
        "Step.Diag.Uptime"    = "Verificando tempo de atividade..."
        "Step.Reg.Scan"   = "Escaneando registro HKCU..."
        "Step.Reg.MRU"    = "Limpando listas de recentes (MRU)..."
        "Step.Reg.Orphan" = "Removendo chaves orfas de apps..."
        "Step.Reg.Temp"   = "Limpando variaveis temporarias..."
        "Step.Reg.Done"   = "Registro otimizado!"
        "Step.IPDNS.Collect" = "Coletando informacoes de rede..."
        "Step.IPDNS.Done"    = "Analise concluida"

        "AnyDeskClosing"  = "Fechando AnyDesk..."
        "AnyDeskStarting" = "Iniciando AnyDesk..."

        "Admin.ModeBtn"   = "Mode Admin"
        "Admin.Section"   = "ADMIN"

        "UI.Menu.16" = "AnyDesk"
        "UI.Menu.17" = "Status IP/DNS"
        "UI.Menu.18" = "ClickUp"
        "UI.Title.16"= "AnyDesk"
        "UI.Title.17"= "Status de IP e DNS"
        "UI.Title.18"= "ClickUp"
        "UI.Desc.16" = "Encerra e reinicia o AnyDesk. Corrige erros de conexao e acesso remoto."
        "UI.Desc.17" = "Verifica se o IP e fixo ou automatico (DHCP) e exibe os servidores DNS configurados."
        "UI.Desc.18" = "Encerra e reinicia o ClickUp. Corrige travamentos, notificacoes e sincronizacao de tarefas."

        "UI.SectionSys"   = "SISTEMA"
        "UI.BtnViewLog"   = "Ver Log"
        "UI.Selected"     = "Selecionado"


    }
    EN = @{
        MenuTitle   = "IT SELF-HEALING SUPPORT"
        MenuIntro   = "If you are experiencing issues on your computer, we have some automated options that may help."
        MenuChoose  = "Select the number corresponding to the issue and press ENTER."
        MenuOptions = "Available options:"
        OptionExit  = "0 - Exit"
        VoltarMenu  = "Press ENTER or B to return to menu..."
        ResolvidoTitulo = "IT Support Agent"
        ResolvidoTexto  = "An automatic correction was executed.`n`nWas the issue resolved?`n`n- Click Resolved to return to menu.`n- Click Not Resolved to open a ticket."
        BtnResolvido    = "Resolved - Return to Menu"
        BtnNaoResolvido = "Not Resolved - Open Ticket"
        DriverTitulo    = "Wi-Fi Driver Update Required"
        DriverTexto     = "Your Wi-Fi driver is outdated.`n`nThe download has started.`nThe IT team must complete the installation.`n`nClick below to open the ticket."
        BtnAbrirTicket  = "Open Ticket"
        EmailSubject         = "Self-Healing Execution"
        EmailGreeting        = "Hello IT Team,"
        EmailEquipInfo       = "Device information:"
        EmailUser            = "User:"
        EmailMachine         = "Machine:"
        EmailThanks          = "Thank you."
        EmailExecuted        = "I executed the function:"
        EmailPersist         = "However, the issue still persists."
        EmailSupport         = "Please assist with further troubleshooting."
        EmailUnknownFunction = "Function not identified"
        LogoTitle            = "IT Support Agent"
        MenuOption1  = "1 - 8x8 Work issues"
        MenuOption2  = "2 - Outlook issues"
        MenuOption3  = "3 - Google Drive issues"
        MenuOption4  = "4 - Slack issues"
        MenuOption5  = "5 - PC freezing (cache and temp cleanup)"
        MenuOption6  = "6 - Microsoft Teams issues"
        MenuOption7  = "7 - Slow internet (Automatic network diagnostics)"
        MenuOption8  = "8 - Computer diagnostics"
        ChooseOption = "Choose an option"
        TeamsRestarting = "Restarting Microsoft Teams..."
        TeamsClosing    = "Closing Microsoft Teams..."
        TeamsStarting   = "Starting Teams..."
        SlackRestarting = "Restarting Slack..."
        SlackClosing    = "Closing Slack..."
        SlackStarting   = "Starting Slack..."
        DriveRestarting = "Restarting Google Drive..."
        DriveClosing    = "Closing Google Drive..."
        DriveStarting   = "Starting Google Drive..."
        DriveNotFound   = "Google Drive not found."
        OutlookClosing  = "Closing Outlook..."
        OutlookStarting = "Starting Outlook..."
        "8x8Restarting" = "Restarting 8x8 Work..."
        "8x8Closing"    = "Closing 8x8 Work..."
        "8x8Starting"   = "Starting 8x8 Work..."
        "8x8NotFound"   = "8x8 Work not found."
        ClickUpClosing  = "Closing ClickUp..."
        ClickUpStarting = "Starting ClickUp..."
        CleaningCache   = "Cleaning cache..."
        ZoomClosing     = "Closing Zoom..."
        ZoomStarting    = "Starting Zoom..."
        ZoomNotFound    = "Zoom not found on this computer."
        OneDriveClosing = "Closing OneDrive..."
        OneDriveStarting= "Starting OneDrive..."
        OneDriveNotFound= "OneDrive not found on this computer."
        ChromeClosing   = "Closing Google Chrome..."
        ChromeStarting  = "Starting Google Chrome..."
        ChromeNotFound  = "Google Chrome not found on this computer."
        WebexClosing    = "Closing Cisco Webex..."
        WebexStarting   = "Starting Cisco Webex..."
        WebexNotFound   = "Webex not found on this computer."
        WhatsAppClosing = "Closing WhatsApp..."
        WhatsAppStarting= "Starting WhatsApp..."
        WhatsAppNotFound= "WhatsApp not found on this computer."
        DropboxClosing  = "Closing Dropbox..."
        DropboxStarting = "Starting Dropbox..."
        DropboxNotFound = "Dropbox not found on this computer."
        AppNotFound     = "Application not found on this computer."
        "NetworkRepairTitle"        = "INTERNET DIAGNOSTICS AND REPAIR"
        "TestingLatency"            = "Testing latency..."
        "TestingDNS"                = "Testing DNS..."
        "NetworkResult"             = "RESULT"
        "AutoFixTitle"              = "AUTO CORRECTION"
        "NetworkProblemDetected"    = "Issue detected. Running basic repairs..."
        "RepairsApplied"            = "Repairs applied."
        "InternetNormal"            = "Internet appears normal."
        "WifiCheckingTitle"         = "CHECKING WIFI DRIVER"
        "WifiNotFound"              = "WiFi adapter not found."
        "WifiDriverNotFound"        = "Unable to locate WiFi driver."
        "WifiOutdated"              = "WIFI DRIVER OUTDATED!"
        "WifiUpdated"               = "WiFi driver up to date."
        "WifiModelDetected"         = "Detected model"
        "WifiDescription"           = "Description"
        "WifiManufacturer"          = "Manufacturer"
        "WifiInstalledVersion"      = "Installed version"
        "WifiBaselineGeneric"       = "Model not found in baseline, using generic baseline."
        "WifiMinimumRecommended"    = "Minimum recommended version"
        "WifiOpenTicketInstruction" = "Please open a ticket with IT to update the Intel Wi-Fi driver."
        "FuncVerifyWifi"            = "Wi-Fi Driver Verification"
        "WifiDriverTitle"           = "Outdated Wi-Fi Driver"
        "WifiDriverOutdatedMessage" = "The Wi-Fi driver is outdated. Click OK to open the Intel official page and start the download."
        WifiDriverTicketMessage     = "The Wi-Fi driver was outdated. Download started (Intel official). Installation must be completed by the IT team."
        WifiDriverUpdateActionName  = "Wi-Fi Driver Download Started"
        InterfaceLabel    = "Interface"
        TypeLabel         = "Type"
        LinkSpeedLabel    = "Link Speed"
        AverageLatency    = "Average latency"
        NoLatencyResponse = "No latency response"
        DnsOk             = "DNS resolution working properly."
        DnsProblem        = "DNS resolution issue detected."
        DnsFlushing       = "Flushing DNS cache..."
        IpRenewing        = "Renewing IP..."
        # === System diagnostic and cleanup strings ===
        "System.HeaderLine"             = "========================================"
        "System.DiagnosticTitle"        = "        COMPUTER DIAGNOSTIC"
        "System.LabelPC"                = "PC"
        "System.LabelWindows"           = "Windows"
        "System.CpuSection"             = "===== CPU ====="
        "System.CpuUsage"               = "Current usage"
        "System.RamSection"             = "===== RAM MEMORY ====="
        "System.RamTotal"               = "Total"
        "System.RamUsed"                = "In use"
        "System.RamFree"                = "Free"
        "System.DiskSection"            = "===== C DRIVE ====="
        "System.DiskTotal"              = "Total"
        "System.DiskFree"               = "Free"
        "System.DiskLowSpace"           = "WARNING: Low disk space!"
        "System.HealthTitle"            = "PC HEALTH SCORE"
        "System.HealthScore"            = "PC Health"
        "System.StatusLabel"            = "Status"
        "System.StatusGood"             = "GOOD"
        "System.StatusWarning"          = "WARNING"
        "System.StatusCritical"         = "CRITICAL"
        "System.UptimeTitle"            = "SYSTEM UPTIME"
        "System.UptimeLabel"            = "PC has been on for"
        "System.Days"                   = "days"
        "System.Hours"                  = "hours"
        "System.UptimeOk"               = "Uptime within recommended limits."
        "System.UptimeRestartQuestion"  = "Your computer has been on for"
        "System.RestartNow"             = "Do you want to restart now?"
        "System.RestartWindowTitle"     = "IT Support Agent - PC Diagnostic"
        "System.RestartCountdown"       = "Your computer will restart in 40 seconds.`nPlease save your files immediately."
        "System.RestartScheduledTitle"  = "IT Support Agent - Scheduled Restart"
        "System.RestartCancelled"       = "Restart cancelled by user."
        "System.DeepCleanQuestion"      = "For a deeper cleanup, some applications must be closed.`n`nClose them automatically?"
        "System.DeepCleanTitle"         = "Advanced Cache Cleanup"
        "System.CleanStart"             = "Starting cache cleanup..."
        "System.DeepCleanMode"          = "DEEP CLEAN mode activated. Closing applications..."
        "System.SafeCleanMode"          = "SAFE CLEAN mode (applications will remain open)"
        "System.DeepCleaning"           = "Deep cleaning"
        "System.Cleaning"               = "Cleaning"
        "System.SpaceFreed"             = "Freed"
        "System.SpaceFreedConsole"      = "Space freed"
        "System.CleanFinishedTitle"     = "Cleanup Completed"
        "System.CleanFinished"          = "Cleanup completed."
        "System.DiagnosticFunctionName" = "PC Diagnostic"
        "System.CleanFunctionName"      = "Cache and Temporary Files Cleanup"
        "System.CleanupFreedSpace"      = "Freed"
        "System.CleanupTitle"           = "Cleanup Completed"
        # ------------------------------------------------------------------
        # UI Keys - WPF interface labels (ui.psm1)
        # ------------------------------------------------------------------
        "UI.Welcome"       = "Welcome"
        "UI.ReadyMsg"      = "Ready. Select an action from the side menu."
        "UI.Running"       = "Running..."
        "UI.WelcomeSub"    = "Select an option from the sidebar to get started."
        "UI.LogReady"      = "Ready. Select an action from the sidebar."
        "UI.LogCleared"    = "Log cleared."
        "UI.LogStarting"   = "Starting"
        "UI.LogDone"       = "Completed"
        "UI.LogResolved"   = "Issue marked as RESOLVED."
        "UI.LogTicket"     = "Opening support ticket..."
        "UI.LogExit"       = "Exiting..."
        "UI.BtnRun"        = "Run Action"
        "UI.BtnClear"      = "Clear Log"
        "UI.Exit"          = "Exit"
        "UI.StatusIdle"    = "Idle"
        "UI.StatusRunning" = "Running..."
        "UI.StatusDone"    = "Done"
        "UI.StatusError"   = "Error"
        "UI.ProgStarting"  = "Starting..."
        "UI.ProgDone"      = "Completed"
        "UI.DialogDoneTitle" = "Action Completed"
        "UI.DialogDoneText"  = "Was the issue resolved? If not, a support ticket will be opened automatically."
        # === Sidebar menu labels (N matches action number in switch) ===
        "UI.Menu.1"  = "Microsoft Teams"
        "UI.Menu.2"  = "Outlook"
        "UI.Menu.3"  = "Google Drive"
        "UI.Menu.4"  = "Slack"
        "UI.Menu.5"  = "Cache Cleanup"
        "UI.Menu.6"  = "Zoom"
        "UI.Menu.7"  = "OneDrive"
        "UI.Menu.8"  = "Google Chrome"
        "UI.Menu.9"  = "Cisco Webex"
        "UI.Menu.10" = "WhatsApp"
        "UI.Menu.11" = "Dropbox"
        "UI.Menu.12" = "Network Diagnose"
        "UI.Menu.13" = "PC Diagnostic"
        "UI.Menu.14" = "Optimize Registry"
        "UI.Menu.15" = "8x8 Work"
        "UI.Title.1" = "Microsoft Teams"
        "UI.Title.2" = "Microsoft Outlook"
        "UI.Title.3" = "Google Drive"
        "UI.Title.4" = "Slack"
        "UI.Title.5" = "Cache Cleanup"
        "UI.Title.6" = "Zoom"
        "UI.Title.7" = "OneDrive"
        "UI.Title.8" = "Google Chrome"
        "UI.Title.9" = "Cisco Webex"
        "UI.Title.10"= "WhatsApp Desktop"
        "UI.Title.11"= "Dropbox"
        "UI.Title.12"= "Network Diagnostics"
        "UI.Title.13"= "PC Diagnostic"
        "UI.Title.14"= "Optimize HKCU Registry"
        "UI.Title.15"= "8x8 Work"
        "UI.Desc.1"  = "Kills and restarts Teams. Fixes calls, status and loading issues."
        "UI.Desc.2"  = "Closes and restarts Outlook. Fixes sync and startup issues."
        "UI.Desc.3"  = "Restarts Google Drive File Stream. Fixes files not syncing."
        "UI.Desc.4"  = "Restarts Slack. Fixes notifications and messages not loading."
        "UI.Desc.5"  = "Clears Windows temp files, browser cache and recycle bin."
        "UI.Desc.6"  = "Kills and restarts Zoom. Fixes audio, video and connection issues."
        "UI.Desc.7"  = "Restarts OneDrive. Fixes file sync issues with the server."
        "UI.Desc.8"  = "Restarts Chrome and clears cache. Fixes slow loading and errors."
        "UI.Desc.9"  = "Kills and restarts Webex. Fixes audio, video and meeting errors."
        "UI.Desc.10" = "Restarts WhatsApp Desktop. Fixes messages not loading."
        "UI.Desc.11" = "Restarts Dropbox. Fixes file synchronization issues."
        "UI.Desc.12" = "Tests latency, DNS and Wi-Fi driver. Auto-repairs if possible."
        "UI.Desc.13" = "Shows CPU, RAM, disk, health score and system uptime."
        "UI.Desc.14" = "Cleans MRU lists, orphan app keys and temp variables from the user registry."
        "UI.Desc.15" = "Closes and restarts 8x8 Work. Fixes calls, audio and VoIP connection issues."
        "UI.SectionComm"  = "COMMUNICATION"
        "UI.SectionProd"  = "PRODUCTIVITY"
        "UI.SectionApps"  = "APPLICATIONS"
        "Step.App.Close"      = "Closing application..."
        "Step.Waiting"        = "Waiting..."
        "Step.App.Start"      = "Starting application..."
        "Step.Clean.Scan"     = "Scanning cache..."
        "Step.Clean.Apps"     = "Closing applications..."
        "Step.Clean.Temp"     = "Cleaning temp files..."
        "Step.Clean.Browser"  = "Cleaning browser cache..."
        "Step.Clean.Recycle"  = "Emptying recycle bin..."
        "Step.Net.Interface"  = "Detecting interface..."
        "Step.Net.Latency"    = "Testing latency..."
        "Step.Net.DNS"        = "Testing DNS..."
        "Step.Net.Repair"     = "Running auto-repair..."
        "Step.Net.Wifi"       = "Checking Wi-Fi driver..."
        "Step.Diag.SysInfo"   = "Collecting system info..."
        "Step.Diag.CPU"       = "Reading CPU usage..."
        "Step.Diag.RAM"       = "Reading RAM..."
        "Step.Diag.Disk"      = "Reading disk..."
        "Step.Diag.Health"    = "Calculating health score..."
        "Step.Diag.Uptime"    = "Checking uptime..."
        "Step.Reg.Scan"   = "Scanning HKCU registry..."
        "Step.Reg.MRU"    = "Clearing recent lists (MRU)..."
        "Step.Reg.Orphan" = "Removing orphan app keys..."
        "Step.Reg.Temp"   = "Cleaning temp variables..."
        "Step.Reg.Done"   = "Registry optimized!"
        "Step.IPDNS.Collect" = "Collecting network information..."
        "Step.IPDNS.Done"    = "Analysis complete"

        "AnyDeskClosing"  = "Closing AnyDesk..."
        "AnyDeskStarting" = "Starting AnyDesk..."

        "Admin.ModeBtn"   = "Mode Admin"
        "Admin.Section"   = "ADMIN"

        "UI.Menu.16" = "AnyDesk"
        "UI.Menu.17" = "IP/DNS Status"
        "UI.Menu.18" = "ClickUp"
        "UI.Title.16"= "AnyDesk"
        "UI.Title.17"= "IP and DNS Status"
        "UI.Title.18"= "ClickUp"
        "UI.Desc.16" = "Closes and restarts AnyDesk. Fixes connection and remote access errors."
        "UI.Desc.17" = "Checks if the IP is static or automatic (DHCP) and shows the configured DNS servers."
        "UI.Desc.18" = "Closes and restarts ClickUp. Fixes freezes, notifications and task sync issues."

        "UI.SectionSys"   = "SYSTEM"
        "UI.BtnViewLog"   = "View Log"
        "UI.Selected"     = "Selected"


    }
}

function Get-Text($Key) { return $Global:Texts[$Global:Language][$Key] }
Export-ModuleMember -Function Get-Text
